import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // 그라데이션 클래스들
    "bg-gradient-to-r",
    "bg-gradient-to-br",
    "bg-gradient-to-bl",
    "bg-gradient-to-t",
    "from-blue-600",
    "to-purple-600",
    "from-green-600",
    "to-blue-600",
    "from-purple-600",
    "to-pink-600",
    "from-red-600",
    "to-orange-600",
    "from-yellow-600",
    "to-red-600",
    "from-indigo-600",
    "to-purple-600",
    "from-cyan-600",
    "to-blue-600",
    "from-emerald-600",
    "to-teal-600",
    "from-rose-600",
    "to-pink-600",
    "from-violet-600",
    "to-purple-600",
    "from-amber-600",
    "to-orange-600",
    // 다크 그라데이션
    "from-blue-800",
    "to-purple-800",
    "from-green-800",
    "to-blue-800",
    "from-purple-800",
    "to-pink-800",
    "from-red-800",
    "to-orange-800",
    "from-yellow-800",
    "to-red-800",
    "from-indigo-800",
    "to-purple-800",
    "from-cyan-800",
    "to-blue-800",
    "from-emerald-800",
    "to-teal-800",
    "from-rose-800",
    "to-pink-800",
    "from-violet-800",
    "to-purple-800",
    "from-amber-800",
    "to-orange-800",
    // 마크다운 파서 전용 클래스들
    "from-slate-900",
    "via-gray-900",
    "to-slate-900",
    "from-slate-800",
    "via-gray-800",
    "to-slate-800",
    "from-slate-700",
    "via-gray-700",
    "to-slate-700",
    "from-blue-500",
    "to-purple-500",
    "from-red-500",
    "to-pink-500",
    "from-yellow-500",
    "to-orange-500",
    "from-green-500",
    "to-emerald-500",
    "from-cyan-500",
    "to-blue-500",
    "from-white/10",
    "via-transparent",
    "to-white/10",
    "from-blue-500/5",
    "to-purple-500/5",
    "from-red-500/5",
    "to-pink-500/5",
    "from-yellow-500/5",
    "to-orange-500/5",
    "from-green-500/5",
    "to-emerald-500/5",
    // 배경색
    "bg-black",
    "bg-gray-900",
    "bg-gray-800",
    "bg-gray-700",
    "bg-gray-600",
    "bg-gray-500",
    "bg-white",
    "bg-gray-50",
    "bg-gray-100",
    "bg-gray-200",
    "bg-slate-900",
    "bg-slate-800",
    "bg-slate-700",
    "bg-slate-600",
    "bg-slate-500",
    "bg-slate-400",
    "bg-slate-300",
    "bg-slate-200",
    "bg-slate-100",
    "bg-slate-50",
    // 투명도 배경
    "bg-gray-900/50",
    "bg-gray-800/50",
    "bg-gray-700/50",
    "bg-slate-900/50",
    "bg-slate-800/50",
    "bg-slate-700/50",
    "bg-blue-900/20",
    "bg-green-900/20",
    "bg-red-900/20",
    "bg-yellow-900/20",
    "bg-purple-900/20",
    "bg-pink-900/20",
    "bg-indigo-900/20",
    "bg-cyan-900/20",
    // 투명도
    "bg-opacity-80",
    "bg-opacity-90",
    "bg-opacity-95",
    // 텍스트 색상
    "text-white",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
    "text-black",
    "text-slate-100",
    "text-slate-200",
    "text-slate-300",
    "text-slate-400",
    "text-slate-500",
    "text-slate-600",
    "text-slate-700",
    "text-slate-800",
    "text-slate-900",
    "text-blue-300",
    "text-blue-400",
    "text-blue-500",
    "text-blue-600",
    "text-green-300",
    "text-green-400",
    "text-green-500",
    "text-red-300",
    "text-red-400",
    "text-red-500",
    "text-yellow-300",
    "text-yellow-400",
    "text-yellow-500",
    "text-purple-300",
    "text-purple-400",
    "text-purple-500",
    "text-pink-300",
    "text-pink-400",
    "text-pink-500",
    "text-orange-300",
    "text-orange-400",
    "text-orange-500",
    "text-cyan-300",
    "text-cyan-400",
    "text-cyan-500",
    // 테두리
    "border-gray-600",
    "border-gray-700",
    "border-gray-800",
    "border-slate-600",
    "border-slate-700",
    "border-slate-800",
    "border-white",
    "border-blue-500",
    "border-green-500",
    "border-red-500",
    "border-yellow-500",
    "border-purple-500",
    "border-pink-500",
    "border-orange-500",
    "border-cyan-500",
    "border-opacity-20",
    "border-opacity-30",
    "border-blue-500/30",
    "border-green-500/30",
    "border-red-500/30",
    "border-yellow-500/30",
    "border-purple-500/30",
    "border-pink-500/30",
    "border-orange-500/30",
    "border-cyan-500/30",
    // 백드롭 효과
    "backdrop-blur-sm",
    "backdrop-blur-md",
    "backdrop-blur-lg",
    // 그림자
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-3xl",
    // 호버 효과
    "hover:bg-gray-800",
    "hover:bg-gray-700",
    "hover:bg-gray-600",
    "hover:bg-slate-800",
    "hover:bg-slate-700",
    "hover:bg-slate-600",
    "hover:text-white",
    "hover:shadow-lg",
    "hover:shadow-xl",
    "hover:scale-105",
    "hover:scale-110",
    "hover:scale-125",
    // 포커스 효과
    "focus:ring-2",
    "focus:ring-blue-500",
    "focus:ring-purple-500",
    "focus:outline-none",
    // 마크다운 전용 클래스들
    "inline-flex",
    "items-center",
    "gap-1.5",
    "gap-2",
    "gap-3",
    "gap-4",
    "px-3",
    "py-1.5",
    "px-4",
    "py-2",
    "px-5",
    "py-2.5",
    "px-6",
    "py-3",
    "px-8",
    "py-6",
    "mx-1",
    "my-1",
    "my-2",
    "my-6",
    "my-8",
    "my-12",
    "my-16",
    "mb-2",
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-12",
    "mb-14",
    "mb-16",
    "mt-16",
    "mt-18",
    "mt-20",
    "mt-24",
    "mt-28",
    "mt-32",
    "pb-4",
    "pb-6",
    "pb-8",
    "pt-6",
    "pt-8",
    "pt-20",
    "pl-6",
    "pl-8",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "font-mono",
    "font-semibold",
    "font-bold",
    "font-extrabold",
    "font-black",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-4xl",
    "text-5xl",
    "leading-relaxed",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
    "uppercase",
    "italic",
    "underline",
    "line-through",
    "decoration-2",
    "decoration-blue-500",
    "underline-offset-4",
    "border-l-4",
    "border-b-2",
    "border-b-4",
    "border-dotted",
    "relative",
    "absolute",
    "inset-0",
    "top-0",
    "left-0",
    "right-0",
    "bottom-0",
    "z-10",
    "overflow-hidden",
    "overflow-x-auto",
    "flex-shrink-0",
    "animate-pulse",
    "animate-ping",
    "animate-bounce",
    "transition-all",
    "transition-colors",
    "transition-opacity",
    "transition-transform",
    "duration-200",
    "duration-300",
    "duration-500",
    "duration-700",
    "duration-1000",
    "transform",
    "scale-105",
    "scale-110",
    "scale-125",
    "opacity-0",
    "opacity-20",
    "opacity-30",
    "opacity-50",
    "opacity-70",
    "opacity-75",
    "opacity-80",
    "opacity-100",
    "group-hover:opacity-100",
    "group-hover:scale-105",
    "group-hover:scale-110",
    "group-hover:scale-125",
    "group-hover:w-full",
    "w-0",
    "w-1",
    "w-1.5",
    "w-2",
    "w-3",
    "w-4",
    "w-5",
    "w-6",
    "w-8",
    "w-10",
    "w-full",
    "h-0.5",
    "h-1",
    "h-1.5",
    "h-2",
    "h-3",
    "h-4",
    "h-5",
    "h-6",
    "h-8",
    "h-10",
    "h-auto",
    "max-w-full",
    "min-w-[3rem]",
    "text-center",
    "text-left",
    "inline-block",
    "block",
    "flex",
    "space-y-1",
    "space-y-2",
    "space-y-4",
    "break-all",
    "bg-clip-text",
    "text-transparent",
    "border-collapse",
    "border-2",
    "border-4",
    "box-shadow",
    "group",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
